### PR TITLE
Add brazilian portuguese locales

### PR DESCRIPTION
**Pull request by guieiras**
Hi! I have been using this skill for a month with locales in Portuguese (my native language). 

Here are the changes I did on my Alexa skill. 

Thank you for this awesome extension!

### CODE REVIEW

**Comment by mendoncart** [comment]
Obrigado!

**Comment by DEADSEC-SECURITY** [comment]
Does this still work? Cuz amazon is kinda picky with language codes.

**Comment by DEADSEC-SECURITY** [comment]
Seems to be in order and according to amazon guidelines.

**Comment by mendoncart** [comment]
@DEADSEC-SECURITY works fine for me.

**Pull request merged**
