### PR TITLE
Add tailscale integration

### PR DESCRIPTION
**Pull request by MelleD**
This PR makes it possible to start the lambda function as a container and connect to the home assistant via Tailscale VPN. This means that it is not necessary to put your HA on the Internet.

Open points are the adaptation of the wiki and documentation. In addition, you have to clone the repo so that the Docker container can be pushed into its own ECR container in AWS.

In addition, you have to think about how to design the githubaction

If you use PY lamdba directly you now have to adapt the config.py and/or if possible also use ENV variables, then the user no longer has to adapt py at all.

I'm looking forward to feedback.

### CODE REVIEW

**Comment by DEADSEC-SECURITY** [comment]
Please add your proposed changes to the wiki to explain how to use and the features it has

**Comment by MelleD** [comment]
Yes, of course I will do it if the changes are ok with the config.py too. In the end you only have to set the Ha-Url, Ha-Token and auth Tailscale Key. But I will describe the workflow with forking and adding images, but it takes a bit of effort ;)

**Comment by DEADSEC-SECURITY** [comment]
Thats ok with me.

**Comment by DEADSEC-SECURITY** [comment]
Please dont edit the wiki directly. Write any mods or new text in here so I can double check before making the changes permanent

**Comment by MelleD** [comment]
Here are some steps you need to take:

The premise is that Tailscale Integration is installed in HA and the HA instance is available as a node.

1. The Git repo must be forked so that the Docker image for the AWS Lambda can be pushed to a private repository in the Amazon Elastic Container Registry.
2. Create a private repository on AWS [Amazon Elastic Container Registry](https://aws.amazon.com/de/ecr/). The name must be ha-custom-lambda-tailscale for the repo
[AWS Introduction ECR] (https://aws.amazon.com/de/ecr/getting-started/)
3. Create a keypair on AWS to allow github action to push the Docker image
Create AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
[AWS Introduction credentials] (https://docs.aws.amazon.com/de_de/keyspaces/latest/devguide/access.credentials.html#SigV4_credentials)

Remember both carefully because the secret is only displayed once and is required in the next step.

4. Go to your formed repo under settings. Go to secrets and variables. Create two new secrets with AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY from the previous step

5. Then build and push the Docker image under Github Actions.To do this, run .github/workflows/docker-build-push.yml

Congratulations! This is the first step and the result should look like this.

1. Create a new function. Select Container Image at the top
https://docs.aws.amazon.com/de_de/lambda/latest/dg/getting-started.html
2. Name the function alexa-actionable-notifications-function and select the Docker image from the ECR and click create function

3.Click "Add Trigger" and copy your skill id from the previous step from the https://developer.amazon.com/alexa/console/ask
skill

TODO NEXT Step

**Comment by MelleD** [comment]
Ping :)

**Pull request closed without merging**
