### PR TITLE
Add variable responses from Alexa

### PR DESCRIPTION
**Pull request by terryhonn**
Allow Alexa's responses to be included in the service call from HA.

image

 I'm no coder, a hack at best, but this seems to be working well for me. Allows for some fun interactions!

Also, this is my first ever pull request, so I'm most likely doing something wrong. Feel free to change whatever needs changing.

### CODE REVIEW

**Comment by honkerst** [comment]
This looks useful, at the moment I'm automating a TTS back to the Echo to say "OK I'll ask again later" in the event of a "No" response.

**Comment by honkerst** [comment]
Just tested this out. Works really well! It's certainly easier to have a nice progression of messages 

`  - alias: Front door left unlocked for 5 mins
      ...
      for:
        minutes: 5
        ...
    action:
           ...
          response_yes: Okay
          response_no: Okay, I'll check again in fifteen minutes
###################
## Lock unlocked for 15 minutes, trigger Alexa question
##
  - alias: Front door left unlocked for 15 mins
      ...
      for:
        minutes: 20
        ...
    action:
           ...
          response_yes: Okay
          response_no: Okay, I'll check again in an hour or so
###################
## Lock unlocked for 60 minutes, trigger Alexa question
##
  - alias: Front door left unlocked for 60 mins
      ...
      for:
        minutes: 80
        ...
    action:
           ...
          response_yes: Okay
          response_no: Okay, I'll check again in a few hours
###################
## Lock unlocked for 180 minutes, trigger Alexa question
##
  - alias: Front door left unlocked for 180 mins
      ...
      for:
        minutes: 180
        ...
    action:
           ...
          response_yes: Okay
          response_no: Okay, I'll stop asking`

**Comment by keatontaylor** [comment]
I've considered this, but a little background on why I decided against it. Right now the skill is activated from the Alexa Media Player Home Assistant integration, when the skill starts it grabs all the text located in the input_text. alexa_actionable_notification entity (the one you create in the very first step)

The major issue is that home assistant has a hard limit of 255 characters for an input_text entity, and so the reason I didn't add this originally is that with all these fields you could very quickly approach that 255 character limit. 

So this is kinda a double edged sword and I have ideas on how it could be fixed, and at that point extend the fields that can be passed in, but for the moment, I'm wanna hold off on this merge request.

**Comment by terryhonn** [comment]
Understood, thanks for the explanation. I'll just leave this here and you do with it what you will.

**Comment by stevenjev** [comment]
Hey Terry, I've noticed that in your pull requests, you've included your Nabu Casa URL. Although it's still password protected, it's best practice to not share this URL.

**Comment by terryhonn** [comment]
> Hey Terry, I've noticed that in your pull requests, you've included your Nabu Casa URL. Although it's still password protected, it's best practice to not share this URL.

Dang, @stevenjev , I sure did. I'm a git idiot, any way to remove just that commit, or delete the entire PR?

**Pull request closed without merging**
