### PR TITLE
Update lambda_function.py

### PR DESCRIPTION
**Pull request by Timp103**
Change line 19 from a double quote to a single quote. Otherwise when issuing the test phrase it would return "Could not communicate with home assistant"

### CODE REVIEW

**Comment by keatontaylor** [comment]
Huh, syntactically this should make absolutely no difference, does your URL home assistant URL contain single quotes?

**Comment by Timp103** [comment]
No my url does not contain quotes. I do use Nabu Casa and I am not using a token, this was the only way it would work for me. I know that it shouldn't make a difference .

**Comment by Timp103** [comment]
Perhaps you can just add a note to try single quotes if they are experiencing the same problem.

**Comment by k7franklin** [comment]
Here i had the same problem. "Could not comunicate with Home assistant" using double quotes or single quote. I dont know bcz, but my account linking was fine.

**Comment by keatontaylor** [comment]
I don't mind changing it, but can you also update the TOKEN field to be single quotes as well just for consistency

**Pull request merged**
