### PR TITLE
Added Italian

### PR DESCRIPTION
**Pull request by paoloantinori**

### CODE REVIEW

**Comment by faman-github** [comment]
Hi Paolo, taking for granted I have to write in english despite both of us are italian, I would like to compliment you for the italian language addition. Would ask you if the whole project is still working or the large number of updates made it obsolete. I think this function is the most important that can link alexa and echo to the home automation. Wondering why is still missing a core relevance in development. Even mr.Keaton Taylor,despite his excellent work, seems to ceased its support, right?

**Comment by faman-github** [comment]
Hi Paolo, taking for granted I have to write in english despite both of us are italian, I would like to compliment you for the italian language addition. Would ask you if the whole project is still working or the large number of updates made it obsolete. I think this function is the most important that can link alexa and echo to the home automation. Wondering why is still missing a core relevance in development. Even mr.Keaton Taylor,despite his excellent work, seems to ceased its support, right?

**Comment by paoloantinori** [comment]
Hi, the PR is almost 1y old but I don't really know why it's not been merged. I have deployed my own fork with the Italian translation and it's been working fine. No reasons to think anything has changed on Amazon or HA side.

**Comment by faman-github** [comment]
Very nice, thank you! I'm going to try it out this weekend, then.

**Comment by migius** [comment]
in generale mi sembra che il file locale_it_it.json non sia stato tradotto, non è necessario?

**Comment by DEADSEC-SECURITY** [comment]
Does this still work?
The owner is kinda distant from the project so new PR's havent been accepted, I wanted to maintain this but its hard with out access to the repo so I cant really help much.

**Comment by keatontaylor** [comment]
@DEADSEC-SECURITY I am happy to add you as a maintainer. An invite has been sent.

**Comment by DEADSEC-SECURITY** [comment]
Seems to be in order, so merging new language.

**Pull request merged**
