### PR TITLE
Remove duplicate and unnecessary code

### PR DESCRIPTION
**Pull request by gosoares**
I found some duplicated and unnecessary code, and removed it:

- Duplicated methods in `HomeAssistant`: `clear_state`, `get_ha_state`, `_handle_response`
- Duplicated line in `LaunchRequestHandler`
- The `Borg` class was unused
- The function `_handle_response` had a if that was always True, and was unnecessary to suppress the okay at the end.

### CODE REVIEW

**Comment by DEADSEC-SECURITY** [comment]
Did you test this?

Removing the Borg function breaks the app last time I checked cuz it's how the program saves the state.

**Comment by gosoares** [comment]
Yes, it's working perfectly here. Maybe it was used before and not anymore? Because the only state that is being used is the one inside the HomeAssistant object that is recreated in each handler.

**Comment by DEADSEC-SECURITY** [comment]
Ill do some more testing just to make sure. Its a lot of changes.

**Comment by DEADSEC-SECURITY** [comment]
This breaks a hole set of features. Closing PR

**Pull request closed without merging**
