### PR TITLE
Migrate language manifests to make them importable

### PR DESCRIPTION
**Pull request by elmar-hinz**
The language manifests are migrated into a different location, such that they will be imported automatically. The json content has been regenerated by use of the developer console, which is introducing a version number.

Minor adjustments have been made to names:

skill.json: "Alexa actionable notifications"
invocation names: "actionable notifications"

Both are not used to work with this skill. The skill is triggered from the end of Home Assistant by using the **skill id**.

"actionable notifications" is set for all languages. This may be translated in future, albeit not really needed, as pointed out just before.

Note 1:

The importer always shows a warning, that the invocation name must not be identical with the skill name. It does occure no matter what combinations of names you give. I tested for a whole hour. It's oviously a bug of the importer.

It always does reset the invocation name to "change me". You actually have to set it to something else again. The TEST simulater in the developer console will not detect the skill, if you call "open change me". Use anything else i.e. 'actionable notifications'.

Note 2:

I noticed that it is not enough to provide a language manifest file. There has to be an entry in skill.json as well. In this case it is possible to directly import this language without having to import en-US first.

Note 3:

Most manifests are not really translated and still hold english expressions. Doing translations is out of the scope of this commit.

### CODE REVIEW

**Comment by elmar-hinz** [comment]
I did set the version in the language files to 1. As they are versioned by git, we basically don't need them. This versions only make sense in the context of the developer console for the user himself, when he wants to change his language files after import. 

I guess they are set back to 1 during the import anyway, as the import does create a fresh repository owned by the user. In case the versions are not reset, I want to make sure they count from 1.

**Comment by DEADSEC-SECURITY** [comment]
I'm going to review this later today and merge if everything looks fine :)
Thanks for the contribution

**Comment by DEADSEC-SECURITY** [comment]
Merged to a new branch so I can update all languages and make sure it works 100%

**Comment by elmar-hinz** [comment]
Does the importer take a branch different from master at all? You may want to use a fork of the repo to test it.

**Comment by DEADSEC-SECURITY** [comment]
master has the importer stuff. I made a new branch from master called migrating languages.

**Comment by DEADSEC-SECURITY** [comment]
I'm going to review the languages and merge to master if everything checks out.

**Pull request merged**
